  airflow-webserver:
	image: "apache/airflow"
	container_name: "airflow-webserver"
	command:
  	- webserver
  	- -p
  	- "8080"
	entrypoint: airflow
	expose:
  	- "8080"
	ports:
  	- "8080:8080"
	volumes:
  	- ./compose_data/airflow:/usr/local/airflow
	depends_on:
  	- postgres